Repository owncloud/ocis-reva, pull requests merged in 2020-07, with the labels that each got.

#323 Increase transfer token life time to 24h
  changelog/unreleased/allow-datagateway-transfers-24h.md
  pkg/flagset/gateway.go
Labels: bug

#330 add new config options for the http client
  pkg/command/frontend.go
  pkg/command/storageeosdata.go
  pkg/command/storagehomedata.go
  pkg/command/storageocdata.go
  pkg/flagset/gateway.go
Labels: enhancement

#355 [skip-ci] add REVA_FRONTEND_URL & REVA_DATAGATEWAY_URL conf
  docs/testing.md
Labels: QA-team

#347 Improve documentation to mention new skip tags
  docs/testing.md
Labels: QA-team

#384 more detailed storage aspects
  docs/storages.md
Labels: documentation

#392 update reva for url signing
  changelog/unreleased/update-reva-to-20200722.md
  go.mod
  go.sum
  pkg/command/frontend.go
Labels: enhancement

#390 Fix doc typos
  changelog/unreleased/update-docs.md
  docs/storages.md
Labels: documentation

#399 split LDAP filters
  .drone.star
  changelog/unreleased/update-ldap-config.md
  changelog/unreleased/update-reva-to-20200724.md
  go.mod
  go.sum
  pkg/command/authbasic.go
  pkg/command/users.go
  pkg/config/config.go
  pkg/flagset/authbasic.go
  pkg/flagset/users.go
Labels: bug

#407 update reva to v0.1.1-0.20200728071211-c948977dd3a0
  changelog/unreleased/update-reva-to-20200728.md
  go.mod
  go.sum
Labels: enhancement

#406 [Tests-Only] Bump commit id for apiTests
  .drone.star
Labels: QA-team

#405 [docs] Add docs about running tests in CI
  docs/testing.md
Labels: QA-team, documentation

#409 [Tests-Only] Bump commit id for oC10APIAcceptanceTests
  .drone.star
Labels: QA-team

#400 Document additional restrictions for the oc storage
  docs/storages.md
Labels: documentation

#417 [Tests-Only] Bump core commit id for core PR 37753
  .drone.star
Labels: QA-team

#416 [Tests-Only] Bump core commit id for API acceptance tests
  .drone.star
Labels: QA-team

#402 [Tests-Only] Implement EXPECTED_FAILURES_FILE for API acceptance tests
  .codacy.yml
  .drone.star
  .gitignore
  Makefile
  composer.json
  docs/testing.md
  tests/acceptance/config/behat.yml
  tests/acceptance/expected-failures.txt
  tests/acceptance/features/apiOcisSpecific/ocsDELETEAuth.feature
  tests/acceptance/features/apiOcisSpecific/ocsGETAuth.feature
  tests/acceptance/features/apiOcisSpecific/ocsPOSTAuth.feature
  tests/acceptance/features/apiOcisSpecific/ocsPUTAuth.feature
  tests/acceptance/features/bootstrap/RevaContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  vendor-bin/behat/composer.json
Labels: QA-team
