Repository owncloud/ocis-reva, pull requests merged in 2020-04, with the labels that each got.

#129 Toggle traces
  pkg/command/authbasic.go
  pkg/command/authbearer.go
  pkg/command/frontend.go
  pkg/command/gateway.go
  pkg/command/sharing.go
  pkg/command/storageeos.go
  pkg/command/storageeosdata.go
  pkg/command/storagehome.go
  pkg/command/storagehomedata.go
  pkg/command/storageoc.go
  pkg/command/storageocdata.go
  pkg/command/storageroot.go
  pkg/command/users.go
Labels: enhancement

#138 fix user related documentation
  README.md
  docs/users.md
Labels: QA-team, documentation

#140 [Tests-Only] improve testing documentation
  docs/testing.md
Labels: QA-team, documentation

#141 [Tests-Only] document how to use oC10 API tests for BDD in ocis
  docs/testing.md
Labels: QA-team, documentation

#142 [Tests-only] delete test documentation from README
  README.md
  docs/testing.md
Labels: QA-team, documentation

#143 fix links to documentation
  README.md
Labels: documentation
