Repository owncloud/ocis-reva, pull requests merged in 2020-02, with the labels that each got.

#73 [Tests-only] run LDAP as service in CI
  .drone.star
Labels: QA-team

#77 allow different namespaces
  .drone.star
  changelog/unreleased/pull-77.md
  pkg/command/frontend.go
  pkg/config/config.go
  pkg/flagset/frontend.go
Labels: bug

#86 fixing changelog format
  changelog/unreleased/76.md
  changelog/unreleased/change-default-namespace.md
Labels: documentation

#88 expose owncloud storage driver config in flagset
  changelog/unreleased/issue-87.md
  pkg/command/storagehome.go
  pkg/command/storagehomedata.go
  pkg/command/storageoc.go
  pkg/command/storageocdata.go
  pkg/command/storageroot.go
  pkg/config/config.go
  pkg/flagset/storagehome.go
  pkg/flagset/storagehomedata.go
  pkg/flagset/storageoc.go
  pkg/flagset/storageocdata.go
  pkg/flagset/storageroot.go
Labels: enhancement

#80 [Tests-only] documentation about running oC10 API tests
  README.md
Labels: QA-team, documentation

#90 storage providers now default to exposing data servers
  .drone.star
  README.md
  changelog/unreleased/issue-89.md
  pkg/flagset/storagehome.go
  pkg/flagset/storageoc.go
Labels: enhancement

#93 cleanup readme
  README.md
Labels: documentation

#96 [tests-only] run redis server for api tests
  .drone.star
  README.md
Labels: QA-team

#103 [Tests-only] Do not run local storage tests
  .drone.star
Labels: QA-team
