Repository owncloud/ocis-reva, pull requests merged in 2020-05, with the labels that each got.

#162 [Tests-only] fixtures and clarifications for API acceptance tests
  docs/testing.md
Labels: QA-team, documentation

#161 update reva, includes tus support
  go.mod
  go.sum
Labels: enhancement

#185 [Tests-only] Create test-skeleton files while creating user
  .drone.star
Labels: QA-team

#201 [Tests-only] Fix skeleton directory path
  .drone.star
Labels: QA-team

#209 [Tests-Only] use latest version of phoenix for UI tests in CI
  .drone.star
Labels: QA-team

#223 [Tests-Only] Fix upload UI tests in CI
  .drone.star
Labels: QA-team
