Repository owncloud/ocis-reva, pull requests merged in 2020-01, with the labels that each got.

#4 separate reva services
  README.md
  changelog/unreleased/issue-6.md
  docker/Dockerfile.linux.amd64
  docker/Dockerfile.linux.arm
  docker/Dockerfile.linux.arm64
  docs/content/about.md
  docs/content/building.md
  docs/content/getting-started.md
  docs/content/users.md
  go.mod
  go.sum
  pkg/command/authbasic.go
  pkg/command/authbearer.go
  pkg/command/frontend.go
  pkg/command/gateway.go
  pkg/command/legacy.go
  pkg/command/root.go
  pkg/command/server.go
  pkg/command/sharing.go
  pkg/command/storagehome.go
  pkg/command/storagehomedata.go
  pkg/command/storageoc.go
  pkg/command/storageocdata.go
  pkg/command/storageroot.go
  pkg/command/users.go
  pkg/config/config.go
  pkg/flagset/authbasic.go
  pkg/flagset/authbearer.go
  pkg/flagset/flagset.go
  pkg/flagset/frontend.go
  pkg/flagset/gateway.go
  pkg/flagset/health.go
  pkg/flagset/root.go
  pkg/flagset/server.go
  pkg/flagset/sharing.go
  pkg/flagset/storagehome.go
  pkg/flagset/storagehomedata.go
  pkg/flagset/storageoc.go
  pkg/flagset/storageocdata.go
  pkg/flagset/storageroot.go
  pkg/flagset/users.go
  pkg/server/debug/option.go
  pkg/server/debug/server.go
Labels: enhancement

#8 fix default storage config
  pkg/flagset/storagehomedata.go
  pkg/flagset/storageoc.go
  pkg/flagset/storageocdata.go
Labels: bug

#19 Fix desktop oidc
  pkg/command/frontend.go
Labels: bug

#7 add .github folder
  .github/issue_template.md
  .github/pull_request_template.md
  .github/settings.yml
Labels: bug

#68 change default ocdav namespace
  changelog/unreleased/change-default-namespace.md
  pkg/command/frontend.go
  pkg/config/config.go
  pkg/flagset/frontend.go
Labels: enhancement

#59 run API tests from oC 10 in CI
  .drone.star
Labels: QA-team
